### ISSUE TITLE
Bug in 10.1

### ISSUE THREAD

**Issue by GeoRam2016** [orionshock/InFlight#10]
Hi

I have a Bug Found in Patch 10.1

When I flight from Loamm to Schattenzuflucht. Tells me this Error after Landing

131x InFlight/InFlight.lua:588: table index is nil
[string "@InFlight/InFlight.lua"]:588: in function <InFlight/InFlight.lua:536>
[string "@InFlight/InFlight.lua"]:665: in function `?'
[string "@InFlight_Load/InFlight_Load.lua"]:3: in function <InFlight_Load/InFlight_Load.lua:3>

Locals:
this = InFlight {
 0 = <userdata>
 defaults = <table> {
 }
 ADDON_LOADED = <function> defined @InFlight_Load/InFlight_Load.lua:15
 StartTimer = <function> defined @InFlight/InFlight.lua:429
 PLAYER_ENTERING_WORLD = <function> defined @InFlight/InFlight.lua:647
 Print = <function> defined @InFlight/InFlight.lua:160
 GetFlightTime = <function> defined @InFlight/InFlight.lua:182
 GetDestination = <function> defined @InFlight/InFlight.lua:176
 InitSource = <function> defined @InFlight/InFlight.lua:386
 StartMiscFlight = <function> defined @InFlight/InFlight.lua:472
 db = <table> {
 }
 L = <table> {
 }
 PLAYER_LEAVING_WORLD = <function> defined @InFlight/InFlight.lua:641
 debug = false
 LFG_PROPOSAL_DONE = <function> defined @InFlight/InFlight.lua:631
 ShowOptions = <function> defined @InFlight/InFlight.lua:793
 PLAYER_CONTROL_GAINED = <function> defined @InFlight/InFlight.lua:657
 LFG_PROPOSAL_SUCCEEDED = <function> defined @InFlight/InFlight.lua:636
 PrintD = <function> defined @InFlight/InFlight.lua:167
 TAXIMAP_OPENED = <function> defined @InFlight_Load/InFlight_Load.lua:31
 UpdateLook = <function> defined @InFlight/InFlight.lua:680
 SetLayout = <function> defined @InFlight/InFlight.lua:755
}
a1 = 3
oldTime = nil
newTime = 135
msg = "Loamm >>>>> Schattenzuflucht |cff208080Flugzeit hinzugefügt:|r 2:15"
(*temporary) = <table> {
 name = "Loamm"
}
(*temporary) = nil
(*temporary) = "|r "
(*temporary) = "2:15"
(*temporary) = 135
(*temporary) = "2:15"
(*temporary) = "%d:%02d"
(*temporary) = 2.250000
(*temporary) = 15
(*temporary) = "2:15"
(*temporary) = "table index is nil"
elapsed = 0
throt = 0.188679
totalTime = 135.265000
GetTime = <function> defined =[C]:-1
startTime = 205268.920000
takeoff = nil
UnitOnTaxi = <function> defined =[C]:-1
ontaxi = nil
sb = InFlightBar {
 0 = <userdata>
}
inworld = true
PrintD = <function> defined @InFlight/InFlight.lua:167
porttaken = nil
taxiSrc = 2863
vars = <table> {
 2511 = <table> {
 }
 2512 = <table> {
 }
 2513 = <table> {
 }
 2514 = <table> {
 }
 2515 = <table> {
 }
 631 = <table> {
 }
 2517 = <table> {
 }
 2518 = <table> {
 }
 2519 = <table> {
 }
 2520 = <table> {
 }
 1774 = <table> {
 }
 1520 = <table> {
 }
 1017 = <table> {
 }
 2528 = <table> {
 }
 2529 = <table> {
 }
 1778 = <table> {
 }
 1018 = <table> {
 }
 635 = <table> {
 }
 1524 = <table> {
 }
 1019 = <table> {
 }
 40 = <table> {
 }
 2537 = <table> {
 }
 56 = <table> {
 }
 80 = <table> {
 }
 383 = <table> {
 }
 128 = <table> {
 }
 160 = <table> {
 }
 192 = <table> {
 }
 894 = <table> {
 }
 256 = <table> {
 }
 2548 = <table> {
 }
 384 = <table> {
 }
 895 = <table> {
 }
 1023 = <table> {
 }
 2045 = <table> {
 }
 2046 = <table> {
 }
 1025 = <table> {
 }
 2558 = <table> {
 }
 2559 = <table> {
 }
 2560 = <table> {
 }
 2561 = <table> {
 }
 258 = <table> {
 }
 2564 = <table> {
 }
 386 = <table> {
 }
 2569 = <table> {
 }
 259 = <table> {
 }
 645 = <table> {
 }
 2062 = <table> {
 }
 130 = <table> {
 }
 646 = <table> {
 }
 226 = <table> {
 }
 260 = <table> {
 }
 324 = <table> {
 }
 2584 = <table> {
 }
 2585 = <table> {
 }
 2075 = <table> {
 }
 521 = <table> {
 }
 649 = <table> {
 }
 2589 = <table> {
 }
 2590 = <table> {
 }
 522 = <table> {
 }
 163 = <table> {
 }
 651 = <table> {
 }
 390 = <table> {
 }
 652 = <table> {
 }
 2090 = <table> {
 }
 2091 = <table> {
 }
 525 = <table> {
 }
 82 = <table> {
 }
 781 = <table> {
 }
 2095 = <table> {
 }
 526 = <table> {
 }
 654 = <table> {
 }
 1052 = <table> {
 }
 The Sin'loren = <table> {
 }
 1053 = <table> {
 }
 1054 = <table> {
 }
 656 = <table> {
 }
 1055 = <table> {
 }
 1056 = <table> {
 }
 657 = <table> {
 }
 1568 = <table> {
 }
 2111 = <table> {
 }
 1058 = <table> {
 }
 658 = <table> {
 }
 531 = <table> {
 }
 659 = <table> {
 }
 1572 = <table> {
 }
 458 = <table> {
 }
 1573 = <table> {
 }
 66

**Comment by orionshock** [comment]
Sorry i don't support Retail for InFlight; 

I've forked and completely rewritten from scratch the basic idea as OnFlight and only support Classic

**Comment by JourneyOver** [comment]
Honestly decided to just randomly test this after coming across it while searching for a new flight timer even though I know that this addon is for wrath classic and probably wouldn't work but from what I can tell it is working just fine in retail as well right now without any errors. The only thing that seems to be missing really is the flight timers in the tooltips on the actual flight map after the flight times have been added in for said paths.
