### ISSUE TITLE
Idea: Record Flight time once

### ISSUE THREAD

**Issue by Kulturnilpferd** [orionshock/InFlight#11]
If you could just fly every route you could save the data in the addon so you never need to "record" the flight times...

**Comment by orionshock** [comment]
I'm not sure what your trying to say or ask for.

Yes, eventually all the flights will get logged and added.

For me to do this myself is just a huge time sink and while I do try, it's not a fast process.

If you'd like to contribute your data, please upload it here I'll get it processed in.
