### ISSUE TITLE
Gossip flights don't seem to work

### ISSUE THREAD

**Issue by adamk33n3r** [orionshock/InFlight#5]
I used to have the old version that ran using `GossipTitleButton_OnClick` but as of today's update that doesn't exist anymore. So I updated to this version, and it doesn't throw an error but it also doesn't work.

**Comment by orionshock** [comment]
what flight where? not all of them are supported.
I only put in a few of the quest ones, not all of them.

**Comment by adamk33n3r** [comment]
I was testing the one from Moonglade to Darnassus for Druids. Which I'm fairly confident worked before the patch.

**Comment by orionshock** [comment]
Default UI now has 2 different API's that can be used for Gossip Text options like this. I think the default UI is using the other one that was introduced in retail back in shadowlands. Will have a fix soon.

**Comment by orionshock** [comment]
fixed in v3.7.12
