### ISSUE TITLE
Can't find/open callbackhandler

### ISSUE THREAD

**Issue by gravitas425** [orionshock/InFlight#9]
55x OnFlight/embeds.xml:3 Couldn't open OnFlight/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.xml

55x Interface_Wrath\FrameXML\Bindings.xml:1 OnFlight/embeds.xml:3 Couldn't open OnFlight/libs/CallbackHandler-1.0/CallbackHandler-1.0.xml

**Comment by orionshock** [comment]
fixed
